### ISSUE TITLE
Fabric Server Crash on Start up. [Bug]: 

### ISSUE THREAD

**Issue by riversofrios** [TheIllusiveC4/Consecration#76]
### Minecraft Version

1.20.1

### What happened?

Server crashes on launch giving error of spectrelib

I don't have a spectrelib so I'm assuming its built into the mod?

Help is appreciated.

### How do you trigger this bug?

1. Botted up on Fabric server modloader.
2. Crash Report
3. Panic

### Loader

Fabric

### Loader Version

fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2

### Mod Version

consecration-fabric-7.0.0+1.20.1

### Relevant Log Outputs

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5321.method_29180(class_5321.java:35)
	at net.minecraft.class_7924.method_47517(class_7924.java:200)
	at net.minecraft.class_7924.<clinit>(class_7924.java:93)
	at com.illusivesoulworks.consecration.common.impl.HolySources.<clinit>(HolySources.java:170)
	at com.illusivesoulworks.consecration.common.config.ConsecrationConfig.lambda$setup$0(ConsecrationConfig.java:50)
	at com.illusivesoulworks.spectrelib.config.SpectreConfig.fireLoad(SpectreConfig.java:117)
	at com.illusivesoulworks.spectrelib.config.SpectreConfigTracker.lambda$loadGlobalConfigs$2(SpectreConfigTracker.java:94)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783)
	at com.illusivesoulworks.spectrelib.config.SpectreConfigTracker.loadGlobalConfigs(SpectreConfigTracker.java:86)
	at com.illusivesoulworks.spectrelib.config.SpectreConfigEvents.onLoadGlobal(SpectreConfigEvents.java:25)
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:35)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at net.minecraft.class_2966.method_36237(class_2966.java:123)
	at net.minecraft.class_2966.method_36235(class_2966.java:116)
	at net.minecraft.class_2370.<init>(class_2370.java:102)
	at net.minecraft.class_2370.<init>(class_2370.java:98)
	at net.minecraft.class_7923.<clinit>(class_7923.java:115)
	... 18 more

**Comment by SlimeyIceCream** [comment]
I got a very similar error message on quilt

**Comment by E3VL** [comment]
Same thing on 7.0.1

**Comment by TheIllusiveC4** [comment]
Very sorry for the delay on this, it should now be fixed on both Fabric and Quilt as of 7.0.2.
